### ISSUE TITLE
esporre la struttura dei dati attesi tramite marshmallow-jsonschema

### ISSUE THREAD

**Issue by gvaldambrini** [mwcschool/ecommerce_api#26]
Utilizzare [marshmallow-jsonschema](https://github.com/fuhrysteve/marshmallow-jsonschema) per creare i json schema relativi a come sono strutturati i dati delle richieste.

**Comment by GendoIkari** [comment]
- Creare un metodo `verify_json` in classe base model che verifica che il json passato come parametro sia corretto, testandolo sul jsonschema creato da marshmallow-jsonschema.
Marshmallow-jsonschema genera il jsonschema, e il modulo jsonschema e' usato per validare il json in arrivo con il jsonschema.
https://pypi.python.org/pypi/jsonschema
