### ISSUE TITLE
Studio fatibilita' per usare cloudinary

### ISSUE THREAD

**Issue by GendoIkari** [mwcschool/ecommerce_api#73]
Valutare come integrare cloudinary, o un servizio analogo, se possibile, per non avere immagini su disco in locale in produzione.

http://cloudinary.com/

**Comment by Soraph** [comment]
Ho realizzato un branch (https://github.com/Soraph/ecommerce_api/tree/73_cloudinary) con un esempio di integrazione.

Cloudinary funziona anche come addon Heroku senza aver bisogno di configurazioni speciali.
